careconnect/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views
app_name = "main"

urlpatterns = [
 path("signup/", views.SignupView.as_view(), name="signup"),
 path("login/", views.LoginView.as_view(), name="login"),
 path("", views.HomePageView.as_view(), name="home"),
 path("about/", views.AboutPageView.as_view(), name="about"),
 path("contact/", views.ContactPageView.as_view(), name="contact"),
 path("profile/", views.ProfilePageView.as_view(), name="profile"),
 path("open_chat/", views.OpenChatPageView.as_view(), name="open_chat"),
 path("chat_detail/<uuid:chat_id>/", views.ChatDetailPageView.as_view(), name="chat_detail"),
 path("messages/<uuid:chat_id>/" , views.MessagesPageView.as_view(), name="messages"),
 path("posts/<int:region_id>/", views.PostsPageView.as_view(), name="posts"),
 path("posts_detail/<int:post_id>/", views.PostsDetailPageView.as_view(), name="posts_detail"),
 path("volonter/", views.VolonterPageView.as_view(), name="volonter"),
 path("logout/", views.LogoutView.as_view(), name="logout"),
 path("delete_chat/<uuid:chat_id>/", views.DeleteChatView.as_view(), name="delete_chat"),

]

templates/admin.html
     <!doctype html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    {% load static %}
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Admin | IVP</title>
    <meta name="robots" content="noindex, follow" />
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="assets/images/favicon.png">

    <!-- CSS
    ============================================ -->

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/vendor/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/slick.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/slick-theme.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/base.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugins/plugins.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
</head>

<body>

    <div class="main-wrapper">
        <div class="mouse-cursor cursor-outer"></div>
        <div class="mouse-cursor cursor-inner"></div>

        <div id="my_switcher" class="my_switcher">
            <ul>
                <li>
                    <a href="javascript: void(0);" data-theme="light" class="setColor light">
                        <span title="Light Mode">Light</span>
                    </a>
                </li>
                <li>
                    <a href="javascript: void(0);" data-theme="dark" class="setColor dark">
                        <span title="Dark Mode">Dark</span>
                    </a>
                </li>
            </ul>
        </div>

      

        



        
        <!-- Start Post Grid Area  -->
        <a href="{% url 'main:logout' %}"><button class="axil-button button-rounded btn-primary">Log Out</button></a>
        <div class="axil-post-grid-area axil-section-gap bg-color-white">
         <div class="container">
             <div class="row align-items-center">
                 <div class="col-lg-6 col-md-8 col-sm-8 col-12">
                     <div class="section-title">
                         <h2 class="title">Message Regions</h2>
                     </div>
                 </div>
            
             </div>
             <div class="row">
                <div class="col-lg-12 col-xl-12">
                    <!-- Start Post List  -->
                    {% if chats_with_last_message %}
                    {% for chat, last_message in chats_with_last_message %}
                        <div class="content-block post-list-view mt--30">
                            <div class="post-content">
                                <div class="post-cat">
                                    <div class="post-cat-list">
                                        <a class="hover-flip-item-wrapper" href="#">
                                            <span class="hover-flip-item">
                                                <span data-text="{{ last_message.sender.username }}">{{ last_message.sender.username }}</span>
                                            </span>
                                        </a>
                                    </div>
                                </div>
                                <h4 class="title"><a href="{% url 'main:chat_detail' chat.id %}">{{ last_message.sender.username }}</a></h4>
                                <div class="post-meta-wrapper">
                                    <div class="post-meta">
                                        <div class="content">
                                            <ul class="post-meta-list">
                                                {% if last_message %}
                                                    <li><b>Last message by {{ last_message.sender.username }} at {{ last_message.timestamp|date:"M d, Y" }}: {{ last_message.content }}</b></li>
                                                {% else %}
                                                    <li>No messages yet</li>

                                                {% endif %}
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <h1>No messages yet</h1>
                  
                   
                {% endif %}

                  

                </div>
             </div>

         </div>
     </div>
     <!-- End Post Grid Area  -->


        <!-- Start Back To Top  -->
        <a id="backto-top"></a>
        <!-- End Back To Top  -->

    </div>

    <!-- JS
============================================ -->
    <!-- Modernizer JS -->
    <script src="{% static 'assets/js/vendor/modernizr.min.js' %}"></script>
    <!-- jQuery JS -->
    <script src="{% static 'assets/js/vendor/jquery.js' %}"></script>
    <!-- Bootstrap JS -->
    <script src="{% static 'assets/js/vendor/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/slick.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/tweenmax.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/js.cookie.js' %}"></script>
    <script src="{% static 'assets/js/vendor/jquery.style.switcher.js' %}"></script>


    <!-- Main JS -->
    <script src="assets/js/main.js"></script>

</body>

</html>

templates/login.html
<!doctype html>
<html class="no-js" lang="en">

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Log In | IVP</title>
    <meta name="robots" content="noindex, follow" />
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="assets/images/favicon.png">

    <!-- CSS
    ============================================ -->

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/vendor/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/slick.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/slick-theme.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/base.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugins/plugins.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    

</head>

<body>
    <div class="main-wrapper">
        <div class="mouse-cursor cursor-outer"></div>
        <div class="mouse-cursor cursor-inner"></div>

        <div id="my_switcher" class="my_switcher">
            <ul>
                <li>
                    <a href="javascript: void(0);" data-theme="light" class="setColor light">
                        <span title="Light Mode">Light</span>
                    </a>
                </li>
                <li>
                    <a href="javascript: void(0);" data-theme="dark" class="setColor dark">
                        <span title="Dark Mode">Dark</span>
                    </a>
                </li>
            </ul>
        </div>
  

    


        

        <!-- Start Post Single Wrapper  -->
        <div class="post-single-wrapper axil-section-gap bg-color-white">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="axil-post-details">
                            
                         
                          
                           
                            


                       

                          
                         

                            <!-- Start Comment Form Area  -->
                            <div class="axil-comment-area" >
                            

                                <!-- Start Comment Respond  -->
                                <div class="comment-respond">
                                    {% if messages %}
                                        {% for message in messages %}
                                            <h4 class="{{ message.tags }}">{{ message }}</h4>
                                        {% endfor %}
                                {% endif %} 
                                    <h4 class="title">Log In</h4>
                                    <form action="{% url 'main:login' %}" method="post">
                                        {% csrf_token %}
                                        <p class="comment-notes"><span id="email-notes">Don't have an account?</span> <a href="{% url 'main:signup'%}">Sign Up</a> <span
                                            class="required"></span></p>
                                        <div class="row row--10">
                                            
                                           
                                          
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <label>Email*</label>
                                                    <input type="text" name="email" >
                                                    <label>Password*</label>
                                                 <input type="password" name="password" >
                                                </div>
                                            </div>
                                      
                                            
                                            
                                          
                                            <div class="col-lg-12">
                                                <div class="form-submit cerchio">
                                                    <input name="submit" type="submit" id="submit" class="axil-button button-rounded" value="Log In">
                                                </div>
                                            </div>
                                            
                                        </div>
                                    </form>
                                </div>
                                <!-- End Comment Respond  -->

                               

                            </div>
                            <!-- End Comment Form Area  -->


                        </div>
                    </div>
                   
                </div>
            </div>
        </div>
        <!-- End Post Single Wrapper  -->

     

        


    </div>

    <!-- JS
============================================ -->
    <!-- Modernizer JS -->
    <script src="{% static 'assets/js/vendor/modernizr.min.js' %}"></script>
    <!-- jQuery JS -->
    <script src="{% static 'assets/js/vendor/jquery.js' %}"></script>
    <!-- Bootstrap JS -->
    <script src="{% static 'assets/js/vendor/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/slick.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/tweenmax.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/js.cookie.js' %}"></script>
    <script src="{% static 'assets/js/vendor/jquery.style.switcher.js' %}"></script>
    
    <!-- Main JS -->
    <script src="{% static 'assets/js/main.js' %}"></script>
    

</body>

</html>

templates/messages.html
<!doctype html>
<html class="no-js" lang="en">

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Chat | IVP </title>
    <meta name="robots" content="noindex, follow" />
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="assets/images/favicon.png">

    <!-- CSS
    ============================================ -->

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/vendor/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/slick.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/slick-theme.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/base.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugins/plugins.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">

    

</head>

<body>
    <div class="main-wrapper">
        <div class="mouse-cursor cursor-outer"></div>
        <div class="mouse-cursor cursor-inner"></div>

        <div id="my_switcher" class="my_switcher">
            <ul>
                <li>
                    <a href="javascript: void(0);" data-theme="light" class="setColor light">
                        <span title="Light Mode">Light</span>
                    </a>
                </li>
                <li>
                    <a href="javascript: void(0);" data-theme="dark" class="setColor dark">
                        <span title="Dark Mode">Dark</span>
                    </a>
                </li>
            </ul>
        </div>


 <!-- Start Post Single Wrapper  -->
 <div class="post-single-wrapper axil-section-gap bg-color-white">
  <div class="container">
      <div class="row">
          <div class="col-lg-8">
              <div class="axil-post-details">
                  
                  
               
                
                 
                  


             

               
               

                  <!-- Start Comment Form Area  -->
                  <div class="axil-comment-area">
                  


                      <!-- Start Comment Area  -->
                      <div class="axil-comment-area">
                        <h4 class="title"> Chat</h4>
                        <ul class="comment-list">
                            {% for message in messages %}
                            <!-- Start Single Comment  -->
                            <li class="comment">
                                <div class="comment-body">
                                    <div class="single-comment">
                                            {% if message.sender_profile_avatar %}
                                        <div class="comment-img">

                                                <img src="{{ message.sender_profile_avatar }}" alt="Author Avatar">
                                        </div>

                                            {% else %}
                                        <div class="comment-img" style="margin-left: 50px;">

                                                <img src="{% static 'volonter.webp' %}" alt="Default Avatar">
                                        </div>
                                            {% endif %}
                                        <div class="comment-inner">
                                            <h6 class="commenter">
                                                {% if not message.sender_profile_name and not message.sender_profile_surname %}
                                                Volunteer
                                                {% else %}
                                                    {{ message.sender_profile_name }} {{ message.sender_profile_surname }}
                                                {% endif %}
                                            </h6>
                                            <div class="comment-meta">
                                                <div class="time-spent">{{ message.timestamp|date:"M d, Y" }} at {{ message.timestamp|date:"H:i" }}</div>
                                            </div>
                                            <div class="comment-text">
                                                <p class="b2">{{ message.content }}</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <!-- End Single Comment  -->
                            {% endfor %}
                        </ul>
                    </div>
                    <!-- End Comment Area  -->
                    

                      <!-- Start Comment Respond  -->
                      <div class="comment-respond">
                       <form action="{% url 'main:messages' chat.id %}" method="POST">
                        {% csrf_token %}
                         
                           <div class="row row--10">
                               
                              
                             <style>.fixed-bottom-form {
                                position: fixed;
                                bottom: 0;
                                width: 97%;
                                padding: 10px;
                                height: 280px;
                                background-color: black;
                                z-index: 1000;
                            }
                            
                            
                            </style>
                            <div class="fixed-bottom-form">
                                <div class="col-12">
                                    <div class="form-group">
                                        <label for="message">Message</label>
                                        <textarea name="message" id="message"></textarea>
                                    </div>
                                </div>
                        
                                <div class="col-lg-12">
                                    <div class="form-submit cerchio">
                                        <input name="submit" type="submit" id="submit" class="axil-button button-rounded" value="Send">
                                    </div>
                                    <div class="form-submit cerchio">
                                        <a href="{% url 'main:profile' %}">
                                        <input name="submit" type="submit" id="submit" class="axil-button button-rounded" value="Back"></a>
                                    </div>
                                    {% if request.user.is_superuser %}
                                    <div class="form-submit">
                                        <a href="{% url 'main:delete_chat' chat.id %}">
                                        <i class="fa fa-trash">Delete This chat</i>
                                        </a>
                                    </div>
                                    {% endif %}
                                    
                                </div>
                            </div>
                           </div>
                       </form>
                   </div>
                   <!-- End Comment Respond  -->

                  </div>
                  <!-- End Comment Form Area  -->
             
                
              </div>
          </div>
         
      </div>
  </div>
</div>
<!-- End Post Single Wrapper  -->
     

        <!-- Start Footer Area  -->
        <div class="axil-footer-area axil-footer-style-1 bg-color-white">
            <!-- Start Footer Top Area  -->
            <div class="footer-top">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            <!-- Start Post List  -->
                            <div class="inner d-flex align-items-center flex-wrap">
                                <h5 class="follow-title mb--0 mr--20">Follow Us</h5>
                                <ul class="social-icon color-tertiary md-size justify-content-start">
                                    <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                                    <li><a href="#"><i class="fab fa-instagram"></i></a></li>
                                    <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                                    <li><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
                                </ul>
                            </div>
                            <!-- End Post List  -->
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Footer Top Area  -->

            <!-- Start Copyright Area  -->
            <div class="copyright-area">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-lg-9 col-md-12">
                            <div class="copyright-left">
                                <div class="logo">
                                    <a href="{% url 'main:home' %}">
                                        <img class="dark-logo" src="{% static  'assets/images/logo/logo2.png' %}" alt="CC logo">
                                        <img class="light-logo" src="{% static 'assets/images/logo/logo2.png' %}" alt="CC logo">
                                    </a>
                                </div>
                                <ul class="mainmenu justify-content-start">
                                    <li>
                                        <a class="hover-flip-item-wrapper" href="{% url 'main:home' %}">
                                            <span class="hover-flip-item">
                                        <span data-text="Home">Home</span>
                                            </span>
                                        </a>
                                    </li>
                                   
                                    
                                    <li>
                                        <a class="hover-flip-item-wrapper" href="{% url 'main:about' %}">
                                            <span class="hover-flip-item">
                                        <span data-text="About Us">About Us</span>
                                            </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a class="hover-flip-item-wrapper" href="{% url 'main:contact' %}">
                                            <span class="hover-flip-item">
                                        <span data-text="Contact Us">Contact Us</span>
                                            </span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-12">
                            <div class="copyright-right text-start text-lg-end mt_md--20 mt_sm--20">
                                <p class="b3">All Rights Reserved © 2024</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Copyright Area  -->
        </div>
        <!-- End Footer Area  -->

        <!-- Start Back To Top  -->
        <a id="backto-top"></a>
        <!-- End Back To Top  -->
    </div>

    <!-- JS
============================================ -->
    <!-- Modernizer JS -->
    <script src="{% static 'assets/js/vendor/modernizr.min.js' %}"></script>
    <!-- jQuery JS -->
    <script src="{% static 'assets/js/vendor/jquery.js' %}"></script>
    <!-- Bootstrap JS -->
    <script src="{% static 'assets/js/vendor/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/slick.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/tweenmax.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/js.cookie.js' %}"></script>
    <script src="{% static 'assets/js/vendor/jquery.style.switcher.js' %}"></script>
    
    <!-- Main JS -->
    <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>